// register action types
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";


// login request types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";


// set password action types
export const SET_PASSWORD_REQUEST = "SET_PASSWORD_REQUEST";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_FAILURE = "SET_PASSWORD_FAILURE";


// get user details action types
export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";

// get user Table Data action types
export const GET_USER_TABLE_DATA_REQUEST = "GET_USER_TABLE_DATA_REQUEST";
export const GET_USER_TABLE_DATA_SUCCESS = "GET_USER_TABLE_DATA_SUCCESS";
export const GET_USER_TABLE_DATA_FAILURE = "GET_USER_TABLE_DATA_FAILURE";
// get Subuser Table Data action types
export const GET_SUB_USER_TABLE_DATA_REQUEST =
  "GET_SUB_USER_TABLE_DATA_REQUEST";
export const GET_SUB_USER_TABLE_DATA_SUCCESS =
  "GET_SUB_USER_TABLE_DATA_SUCCESS";
export const GET_SUB_USER_TABLE_DATA_FAILURE =
  "GET_SUB_USER_TABLE_DATA_FAILURE";

//release modal
export const HANDLE_RELEASE_NOTE_MODAL = "HANDLE_RELEASE_NOTE_MODAL";

export const LOGOUT = "LOGOUT";

// change password action types
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";


// validate email action types
export const VALIDATE_EMAIL_REQUEST = "VALIDATE_EMAIL_REQUEST";
export const VALIDATE_EMAIL_SUCCESS = "VALIDATE_EMAIL_SUCCESS";
export const VALIDATE_EMAIL_FAILURE = "VALIDATE_EMAIL_FAILURE";
